# Generated by Django 3.1.4 on 2020-12-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20201223_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='created',
            new_name='updated',
        ),
    ]
